services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    healthcheck:
      test: "curl http://localhost:3000/ || exit 1"
      interval: 5s
      timeout: 10s
      retries: 25

  agent:
    build:
      context: ./services/agent
      dockerfile: Dockerfile
