services:
  nginx:
    image: ${IMAGE_REPOSITORY}/nginx:${DOCKER_TAG:-latest}
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-certs:/etc/nginx/ssl
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--no-check-certificate", "--spider", "https://0.0.0.0/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  web:
    image: ${IMAGE_REPOSITORY}/web:${DOCKER_TAG:-latest}
    build:
      target: production
    environment:
      LIVEKIT_URL: ${LIVEKIT_URL}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}

  agent:
    image: ${IMAGE_REPOSITORY}/agent:${DOCKER_TAG:-latest}
    build:
      target: production
    environment:
      LIVEKIT_URL: ${LIVEKIT_URL}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
    volumes:
      - agent-cache:/app/.cache

volumes:
  nginx-certs:
  agent-cache:
