---
name: "Setup docker environment"

description: |
  Setup docker environment: Install Buildkit and login to docker registry

inputs:
  env:
    description: "ENV to be used later"
    required: true

  registry:
    description: "URL for docker container registry"
    required: true

  registry-user:
    description: "Username for login to docker registry"
    required: true

  registry-password:
    description: "Password for login to docker registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-password }}

    - name: Set DOCKER_TAG variable
      shell: bash
      run: echo "DOCKER_TAG=${{ github.sha }}" >> $GITHUB_ENV

    - name: Set ENV variable
      shell: bash
      run: echo "ENV=${{ inputs.env }}" >> $GITHUB_ENV

    - name: Set IMAGE_REPOSITORY variable
      shell: bash
      run: echo "IMAGE_REPOSITORY=${{ inputs.registry }}/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
